### ISSUE TITLE
nil pointer dereference on 32 bit linux

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#928]
**Additional information:**
 - OS: Lubuntu 32 bit
 - IPFS Cluster version: 1f07b3a (modified branch, but same as 1f07b3a except p2p-relay options)
 - Installation method: built from source

**Describe the bug:**
Have seen this a bunch of times today. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a9eb]

goroutine 35654 [running]:
runtime/internal/atomic.Load64(0x99dadac, 0xaa5a120, 0xe222643e)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:194 +0xb
github.com/hashicorp/raft.(*Raft).replicateTo(0x9c78400, 0x99dad80, 0x9e, 0x0, 0x0)
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/replication.go:205 +0xa6
github.com/hashicorp/raft.(*Raft).replicate(0x9c78400, 0x99dad80)
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/replication.go:154 +0x3e0
github.com/hashicorp/raft.(*Raft).startStopReplication.func1()
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/raft.go:488 +0x27
github.com/hashicorp/raft.(*raftState).goFunc.func1(0x9c78400, 0xaa5e660)
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/state.go:146 +0x4c
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/state.go:144 +0x54
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a9eb]

goroutine 35655 [running]:
runtime/internal/atomic.Load64(0x99dae2c, 0xa9f48e0, 0x3fa0bb35)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:194 +0xb
github.com/hashicorp/raft.(*Raft).replicateTo(0x9c78400, 0x99dae00, 0x9e, 0x0, 0x0)
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/replication.go:205 +0xa6
github.com/hashicorp/raft.(*Raft).replicate(0x9c78400, 0x99dae00)
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/replication.go:154 +0x3e0
github.com/hashicorp/raft.(*Raft).startStopReplication.func1()
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/raft.go:488 +0x27
github.com/hashicorp/raft.(*raftState).goFunc.func1(0x9c78400, 0xaa5e680)
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/state.go:146 +0x4c
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/kishan/go/pkg/mod/github.com/hashicorp/raft@v1.1.0/state.go:144 +0x54
```

**Comment by hsanjuan** [comment]
This is a Raft bug that was fixed in Raft: https://github.com/hashicorp/raft/commits/v1.1.1/replication.go

I will run a general dependency upgrade very soon.
